version: "3"
services:
#  backend:
#    build: .
#    restart: always
#    environment:
#      TEST: test
#    ports:
#      - "8081:8013"
#    depends_on:
#      - mysql

  backend_db:
    build: .
    restart: always
    environment:
      TEST: test
      ROUTE: /api/db/
    ports:
      - "8081:8013"
    depends_on:
      - mysql

  backend_external:
    build: .
    restart: always
    environment:
      TEST: test
      ROUTE: /api/external/
    ports:
      - "8082:8013"

  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: "bakson"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - my-db:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend_db
      - backend_external

volumes:
  my-db: